// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	lista "github.com/viniciusfal/erpnet/internal/domain/lista"
)

// CategoriaRepository is an autogenerated mock type for the CategoriaRepository type
type CategoriaRepository struct {
	mock.Mock
}

type CategoriaRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CategoriaRepository) EXPECT() *CategoriaRepository_Expecter {
	return &CategoriaRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, idCategoria
func (_m *CategoriaRepository) Delete(ctx context.Context, idCategoria int64) error {
	ret := _m.Called(ctx, idCategoria)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, idCategoria)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CategoriaRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CategoriaRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - idCategoria int64
func (_e *CategoriaRepository_Expecter) Delete(ctx interface{}, idCategoria interface{}) *CategoriaRepository_Delete_Call {
	return &CategoriaRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, idCategoria)}
}

func (_c *CategoriaRepository_Delete_Call) Run(run func(ctx context.Context, idCategoria int64)) *CategoriaRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *CategoriaRepository_Delete_Call) Return(_a0 error) *CategoriaRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CategoriaRepository_Delete_Call) RunAndReturn(run func(context.Context, int64) error) *CategoriaRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx
func (_m *CategoriaRepository) FindAll(ctx context.Context) ([]lista.Categoria, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []lista.Categoria
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]lista.Categoria, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []lista.Categoria); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]lista.Categoria)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CategoriaRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type CategoriaRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *CategoriaRepository_Expecter) FindAll(ctx interface{}) *CategoriaRepository_FindAll_Call {
	return &CategoriaRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *CategoriaRepository_FindAll_Call) Run(run func(ctx context.Context)) *CategoriaRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *CategoriaRepository_FindAll_Call) Return(_a0 []lista.Categoria, _a1 error) *CategoriaRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CategoriaRepository_FindAll_Call) RunAndReturn(run func(context.Context) ([]lista.Categoria, error)) *CategoriaRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function with given fields: ctx, idCategoria
func (_m *CategoriaRepository) FindById(ctx context.Context, idCategoria int64) (*lista.Categoria, error) {
	ret := _m.Called(ctx, idCategoria)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *lista.Categoria
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*lista.Categoria, error)); ok {
		return rf(ctx, idCategoria)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *lista.Categoria); ok {
		r0 = rf(ctx, idCategoria)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lista.Categoria)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, idCategoria)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CategoriaRepository_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type CategoriaRepository_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - ctx context.Context
//   - idCategoria int64
func (_e *CategoriaRepository_Expecter) FindById(ctx interface{}, idCategoria interface{}) *CategoriaRepository_FindById_Call {
	return &CategoriaRepository_FindById_Call{Call: _e.mock.On("FindById", ctx, idCategoria)}
}

func (_c *CategoriaRepository_FindById_Call) Run(run func(ctx context.Context, idCategoria int64)) *CategoriaRepository_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *CategoriaRepository_FindById_Call) Return(_a0 *lista.Categoria, _a1 error) *CategoriaRepository_FindById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CategoriaRepository_FindById_Call) RunAndReturn(run func(context.Context, int64) (*lista.Categoria, error)) *CategoriaRepository_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, categoria
func (_m *CategoriaRepository) Save(ctx context.Context, categoria *lista.Categoria) error {
	ret := _m.Called(ctx, categoria)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *lista.Categoria) error); ok {
		r0 = rf(ctx, categoria)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CategoriaRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type CategoriaRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - categoria *lista.Categoria
func (_e *CategoriaRepository_Expecter) Save(ctx interface{}, categoria interface{}) *CategoriaRepository_Save_Call {
	return &CategoriaRepository_Save_Call{Call: _e.mock.On("Save", ctx, categoria)}
}

func (_c *CategoriaRepository_Save_Call) Run(run func(ctx context.Context, categoria *lista.Categoria)) *CategoriaRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*lista.Categoria))
	})
	return _c
}

func (_c *CategoriaRepository_Save_Call) Return(_a0 error) *CategoriaRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CategoriaRepository_Save_Call) RunAndReturn(run func(context.Context, *lista.Categoria) error) *CategoriaRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, categoria
func (_m *CategoriaRepository) Update(ctx context.Context, categoria *lista.Categoria) error {
	ret := _m.Called(ctx, categoria)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *lista.Categoria) error); ok {
		r0 = rf(ctx, categoria)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CategoriaRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CategoriaRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - categoria *lista.Categoria
func (_e *CategoriaRepository_Expecter) Update(ctx interface{}, categoria interface{}) *CategoriaRepository_Update_Call {
	return &CategoriaRepository_Update_Call{Call: _e.mock.On("Update", ctx, categoria)}
}

func (_c *CategoriaRepository_Update_Call) Run(run func(ctx context.Context, categoria *lista.Categoria)) *CategoriaRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*lista.Categoria))
	})
	return _c
}

func (_c *CategoriaRepository_Update_Call) Return(_a0 error) *CategoriaRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CategoriaRepository_Update_Call) RunAndReturn(run func(context.Context, *lista.Categoria) error) *CategoriaRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewCategoriaRepository creates a new instance of CategoriaRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoriaRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoriaRepository {
	mock := &CategoriaRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
