// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	lista "github.com/viniciusfal/erpnet/internal/domain/lista"
)

// ListaRepository is an autogenerated mock type for the ListaRepository type
type ListaRepository struct {
	mock.Mock
}

type ListaRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ListaRepository) EXPECT() *ListaRepository_Expecter {
	return &ListaRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, idLista
func (_m *ListaRepository) Delete(ctx context.Context, idLista string) error {
	ret := _m.Called(ctx, idLista)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, idLista)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListaRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ListaRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - idLista string
func (_e *ListaRepository_Expecter) Delete(ctx interface{}, idLista interface{}) *ListaRepository_Delete_Call {
	return &ListaRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, idLista)}
}

func (_c *ListaRepository_Delete_Call) Run(run func(ctx context.Context, idLista string)) *ListaRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ListaRepository_Delete_Call) Return(_a0 error) *ListaRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ListaRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *ListaRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx
func (_m *ListaRepository) FindAll(ctx context.Context) ([]lista.Lista, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []lista.Lista
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]lista.Lista, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []lista.Lista); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]lista.Lista)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListaRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type ListaRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ListaRepository_Expecter) FindAll(ctx interface{}) *ListaRepository_FindAll_Call {
	return &ListaRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *ListaRepository_FindAll_Call) Run(run func(ctx context.Context)) *ListaRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ListaRepository_FindAll_Call) Return(_a0 []lista.Lista, _a1 error) *ListaRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ListaRepository_FindAll_Call) RunAndReturn(run func(context.Context) ([]lista.Lista, error)) *ListaRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function with given fields: ctx, idLista
func (_m *ListaRepository) FindById(ctx context.Context, idLista string) (*lista.Lista, error) {
	ret := _m.Called(ctx, idLista)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *lista.Lista
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*lista.Lista, error)); ok {
		return rf(ctx, idLista)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *lista.Lista); ok {
		r0 = rf(ctx, idLista)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lista.Lista)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, idLista)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListaRepository_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type ListaRepository_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - ctx context.Context
//   - idLista string
func (_e *ListaRepository_Expecter) FindById(ctx interface{}, idLista interface{}) *ListaRepository_FindById_Call {
	return &ListaRepository_FindById_Call{Call: _e.mock.On("FindById", ctx, idLista)}
}

func (_c *ListaRepository_FindById_Call) Run(run func(ctx context.Context, idLista string)) *ListaRepository_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ListaRepository_FindById_Call) Return(_a0 *lista.Lista, _a1 error) *ListaRepository_FindById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ListaRepository_FindById_Call) RunAndReturn(run func(context.Context, string) (*lista.Lista, error)) *ListaRepository_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, _a1
func (_m *ListaRepository) Save(ctx context.Context, _a1 *lista.Lista) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *lista.Lista) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListaRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type ListaRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *lista.Lista
func (_e *ListaRepository_Expecter) Save(ctx interface{}, _a1 interface{}) *ListaRepository_Save_Call {
	return &ListaRepository_Save_Call{Call: _e.mock.On("Save", ctx, _a1)}
}

func (_c *ListaRepository_Save_Call) Run(run func(ctx context.Context, _a1 *lista.Lista)) *ListaRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*lista.Lista))
	})
	return _c
}

func (_c *ListaRepository_Save_Call) Return(_a0 error) *ListaRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ListaRepository_Save_Call) RunAndReturn(run func(context.Context, *lista.Lista) error) *ListaRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *ListaRepository) Update(ctx context.Context, _a1 *lista.Lista) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *lista.Lista) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListaRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ListaRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *lista.Lista
func (_e *ListaRepository_Expecter) Update(ctx interface{}, _a1 interface{}) *ListaRepository_Update_Call {
	return &ListaRepository_Update_Call{Call: _e.mock.On("Update", ctx, _a1)}
}

func (_c *ListaRepository_Update_Call) Run(run func(ctx context.Context, _a1 *lista.Lista)) *ListaRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*lista.Lista))
	})
	return _c
}

func (_c *ListaRepository_Update_Call) Return(_a0 error) *ListaRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ListaRepository_Update_Call) RunAndReturn(run func(context.Context, *lista.Lista) error) *ListaRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewListaRepository creates a new instance of ListaRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewListaRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ListaRepository {
	mock := &ListaRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
